export const carModels = [
  {
    title: 'Audi',
    models: [
      'A6',
      'A3',
      'TT',
      'Q5',
      'A6/S6',
      'A4',
      'A2',
      'Q7',
      'A8',
      'A5/S5',
      'ALLROAD',
      'A1',
      'A7',
      'Q3',
    ],
  },
  {
    title: 'BMW',
    models: ['5', '3', '7', 'Z4', '1', '4', 'X3', 'X1', '2', '6', 'X5', 'X6'],
  },
  { title: 'Cadillac', models: ['ATS', 'CTS', 'SRX', 'BLS', 'ESCALADE'] },
  {
    title: 'Chevrolet',
    models: [
      'EVANDA',
      'AVEO',
      'LACETTI',
      'TRAILBLAZER',
      'LANOS',
      'CAMARO',
      'MALIBU',
      'CAPTIVA',
      'REZZO',
      'COBALT',
      'SPARK',
      'EPICA',
      'VIVA',
      'CRUZE',
      'TAHOE',
      'ORLANDO',
    ],
  },
  {
    title: 'Citroen',
    models: [
      'BERLINGO',
      'C5',
      'C-CROSSER',
      'DS4',
      'C1',
      'C2',
      'C-ELYSEE',
      'DS5',
      'C3',
      'C6',
      'XSARA',
      'C4',
      'C8',
      'DS3',
    ],
  },
  {
    title: 'Daewoo',
    models: ['GENTRA', 'MATIZ', 'ESPERO', 'WINSTORM', 'LANOS', 'NEXIA', 'LEGANZA'],
  },
  {
    title: 'Fiat',
    models: ['DOBLO', 'ALBEA', 'GRANDE PUNTO', 'BRAVA', 'BARCHETTA'],
  },
  {
    title: 'Ford',
    models: [
      'ESCORT',
      'GALAXY',
      'GRANADA',
      'S-MAX',
      'C-MAX',
      'KA',
      'KUGA',
      'ORION',
      'ECOSPORT',
      'MAVERICK',
      'B-MAX',
      'P 100',
      'FIESTA',
      'MONDEO',
      'EDGE',
      'SCORPIO',
      'FOCUS',
      'RANGER',
      'ESCAPE',
      'SIERRA',
      'FUSION',
      'TOURNEO',
      'GRAND',
      'STREET',
    ],
  },
  { title: 'Ford usa', models: [] },
  {
    title: 'Honda',
    models: [
      'JAZZ',
      'LEGEND',
      'HR-V',
      'RIDGELINE',
      'ACCORD',
      'PILOT',
      'CROSSTOUR',
      'CIVIC',
      'STEPWAGON',
      'ELEMENT',
      'CR-V',
      'STREAM',
      'FR-V',
    ],
  },
  { title: 'Hummer', models: ['HUMMER H2', 'HUMMER H3'] },
  {
    title: 'Hyundai',
    models: [
      'ELANTRA',
      'I30',
      'SONATA',
      'ix35',
      'ACCENT',
      'i30',
      'TUCSON',
      'MATRIX',
      'COUPE',
      'I40',
      'EQUUS',
      'TERRACAN',
      'GENESIS',
      'i40',
      'GETZ',
      'TRAJET',
      'GRANDEUR',
      'SANTA FE',
      'GRAND SANTA FE',
      'VELOSTER',
      'i10',
      'SOLARIS',
      'i20',
      'ix55',
    ],
  },
  {
    title: 'Infiniti',
    models: [
      'FX',
      'M45',
      'Q70',
      'QX70',
      'G',
      'QX56',
      'QX4',
      'EX',
      'M',
      'JX',
      'QX50',
      'M35',
      'Q50',
      'QX60',
    ],
  },
  { title: 'Jaguar', models: ['XF', 'XJ', 'X-TYPE', 'S-TYPE'] },
  {
    title: 'Jeep',
    models: ['CHEROKEE', 'LIBERTY', 'COMMANDER', 'GRAND CHEROKEE', 'WRANGLER', 'COMPASS'],
  },
  {
    title: 'Kia',
    models: [
      'CARENS',
      'OPTIMA',
      'SORENTO',
      'QUORIS',
      'CARNIVAL',
      'PICANTO',
      'SOUL',
      'VENGA',
      "CEE'D",
      "PRO CEE'D",
      'SPECTRA',
      'JOICE',
      'CERATO',
      'RIO',
      'SPORTAGE',
      'CLARUS',
      'SEPHIA',
      'MOHAVE',
      'MAGENTIS',
      'SHUMA',
      'OPIRUS',
    ],
  },
  { title: 'Land rover', models: [] },
  {
    title: 'Lexus',
    models: ['ES', 'IS', 'RX', 'GS', 'LS', 'CT', 'GX', 'LX', 'SC'],
  },
  {
    title: 'Mazda',
    models: [
      '323',
      'MAZDA3',
      'MX-5',
      'CX-9',
      '626',
      'MAZDA5',
      'RX-8',
      'TRIBUTE',
      'BT-50',
      'MAZDA6',
      'CX-5',
      'XEDOS 6',
      'MAZDA2',
      'MPV',
      'CX-7',
      'XEDOS 9',
    ],
  },
  {
    title: 'Mercedes',
    models: [
      'A-CLASS',
      'CLS',
      'S-CLASS',
      'GLK-CLASS',
      'B-CLASS',
      'E-CLASS',
      'SL',
      'R-CLASS',
      'C-CLASS',
      'GL-CLASS',
      'SLK',
      'SLS AMG',
      'CLK-CLASS',
      'ML-CLASS',
      'GLA-CLASS',
    ],
  },
  {
    title: 'Mitsubishi',
    models: [
      'CARISMA',
      'GRANDIS',
      'OUTLANDER',
      'SPACE STAR',
      'COLT',
      'L 200',
      'PAJERO',
      'GALANT',
      'LANCER',
      'ASX',
    ],
  },
  {
    title: 'Nissan',
    models: [
      '350 Z',
      'NAVARA',
      'QASHQAI',
      'JUKE',
      'ALMERA',
      'NOTE',
      'TEANA',
      'NP300',
      'MAXIMA',
      'PATHFINDER',
      'TERRANO',
      'MICRA',
      'PATROL',
      'TIIDA',
      'MURANO',
      'PRIMERA',
      'X-TRAIL',
    ],
  },
  {
    title: 'Opel',
    models: [
      'ANTARA',
      'ASTRA',
      'CORSA',
      'TIGRA',
      'INSIGNIA',
      'OMEGA',
      'FRONTERA',
      'ZAFIRA',
      'MOKKA',
      'VECTRA',
      'MERIVA',
      'SPEEDSTER',
      'AGILA',
      'MONTEREY',
    ],
  },
  {
    title: 'Peugeot',
    models: [
      '107',
      '301',
      '207',
      '1007',
      '2008',
      '4008',
      '307',
      '4007',
      '206',
      '408',
      '308',
      '607',
      '208',
      '5008',
      '407',
      '807',
      '3008',
      'RCZ',
      '508',
      'PARTNER',
    ],
  },
  {
    title: 'Renault',
    models: [
      'CLIO',
      'LAGUNA',
      'SCENIC',
      'KOLEOS',
      'ESPACE',
      'LOGAN',
      'SYMBOL',
      'LATITUDE',
      'GRAND',
      'MEGANE',
      'TWINGO',
      'WIND',
      'KANGOO',
      'SANDERO',
      'FLUENCE',
      'DUSTER',
    ],
  },
  {
    title: 'Seat',
    models: ['ALHAMBRA', 'IBIZA', 'ALTEA', 'CORDOBA', 'LEON', 'AROSA', 'EXEO', 'TOLEDO', 'INCA'],
  },
  {
    title: 'Skoda',
    models: ['FABIA', 'RAPID', 'ROOMSTER', 'OCTAVIA', 'SUPERB', 'YETI'],
  },
  {
    title: 'SsangYong',
    models: ['ACTYON', 'RODIUS', 'CHAIRMAN', 'REXTON', 'KORANDO', 'STAVIC', 'MUSSO', 'KYRON'],
  },
  {
    title: 'Subaru',
    models: ['FORESTER', 'LEGACY', 'TRIBECA', 'XV', 'IMPREZA', 'OUTBACK', 'BRZ'],
  },
  {
    title: 'Suzuki',
    models: [
      'GRANDVITARA',
      'SWIFT',
      'KIZASHI',
      'JIMNY',
      'SX4',
      'IGNIS',
      'LIANA',
      'WAGON R+',
      'SPLASH',
    ],
  },
  {
    title: 'Toyota',
    models: [
      'VENZA',
      'COROLLA',
      'LAND CRUISER PRADO',
      'IQ',
      '4RUNNER',
      'GT 86',
      'PREVIA',
      'URBAN CRUISER',
      'AURIS',
      'HIGHLANDER',
      'PRIUS',
      'VERSO',
      'AVENSIS',
      'HILUX',
      'RAV 4',
      'CAMRY',
      'LAND CRUISER',
      'YARIS',
    ],
  },
  {
    title: 'Volkswagen',
    models: [
      'BORA',
      'POLO',
      'TOURAN',
      'UP',
      'GOLF',
      'SCIROCCO',
      'AMAROK',
      'JETTA',
      'SHARAN',
      'PHAETON',
      'PASSAT',
      'TOUAREG',
      'TIGUAN',
    ],
  },
  {
    title: 'Volvo',
    models: [
      'C70',
      'V40',
      'S70',
      'XC60',
      'S40',
      'V70',
      'V50',
      'S60',
      'XC70',
      'C30',
      'S80',
      'XC90',
      'V60',
    ],
  },
  { title: 'ЗАЗ', models: [] },
  { title: 'ТагАЗ', models: [] },
  {
    title: 'Audi',
    models: [
      'A6',
      'A3',
      'TT',
      'Q5',
      'A6/S6',
      'A4',
      'A2',
      'Q7',
      'A8',
      'A5/S5',
      'ALLROAD',
      'A1',
      'A7',
      'Q3',
    ],
  },
  {
    title: 'BMW',
    models: ['5', '3', '7', 'Z4', '1', '4', 'X3', 'X1', '2', '6', 'X5', 'X6'],
  },
  { title: 'Cadillac', models: ['ATS', 'CTS', 'SRX', 'BLS', 'ESCALADE'] },
  {
    title: 'Chevrolet',
    models: [
      'EVANDA',
      'AVEO',
      'LACETTI',
      'TRAILBLAZER',
      'LANOS',
      'CAMARO',
      'MALIBU',
      'CAPTIVA',
      'REZZO',
      'COBALT',
      'SPARK',
      'EPICA',
      'VIVA',
      'CRUZE',
      'TAHOE',
      'ORLANDO',
    ],
  },
  {
    title: 'Citroen',
    models: [
      'BERLINGO',
      'C5',
      'C-CROSSER',
      'DS4',
      'C1',
      'C2',
      'C-ELYSEE',
      'DS5',
      'C3',
      'C6',
      'XSARA',
      'C4',
      'C8',
      'DS3',
    ],
  },
  {
    title: 'Daewoo',
    models: ['GENTRA', 'MATIZ', 'ESPERO', 'WINSTORM', 'LANOS', 'NEXIA', 'LEGANZA'],
  },
  {
    title: 'Fiat',
    models: ['DOBLO', 'ALBEA', 'GRANDE PUNTO', 'BRAVA', 'BARCHETTA'],
  },
  {
    title: 'Ford',
    models: [
      'ESCORT',
      'GALAXY',
      'GRANADA',
      'S-MAX',
      'C-MAX',
      'KA',
      'KUGA',
      'ORION',
      'ECOSPORT',
      'MAVERICK',
      'B-MAX',
      'P 100',
      'FIESTA',
      'MONDEO',
      'EDGE',
      'SCORPIO',
      'FOCUS',
      'RANGER',
      'ESCAPE',
      'SIERRA',
      'FUSION',
      'TOURNEO',
      'GRAND',
      'STREET',
    ],
  },
  { title: 'Ford usa', models: [] },
  {
    title: 'Honda',
    models: [
      'JAZZ',
      'LEGEND',
      'HR-V',
      'RIDGELINE',
      'ACCORD',
      'PILOT',
      'CROSSTOUR',
      'CIVIC',
      'STEPWAGON',
      'ELEMENT',
      'CR-V',
      'STREAM',
      'FR-V',
    ],
  },
  { title: 'Hummer', models: ['HUMMER H2', 'HUMMER H3'] },
  {
    title: 'Hyundai',
    models: [
      'ELANTRA',
      'I30',
      'SONATA',
      'ix35',
      'ACCENT',
      'i30',
      'TUCSON',
      'MATRIX',
      'COUPE',
      'I40',
      'EQUUS',
      'TERRACAN',
      'GENESIS',
      'i40',
      'GETZ',
      'TRAJET',
      'GRANDEUR',
      'SANTA FE',
      'GRAND SANTA FE',
      'VELOSTER',
      'i10',
      'SOLARIS',
      'i20',
      'ix55',
    ],
  },
  {
    title: 'Infiniti',
    models: [
      'FX',
      'M45',
      'Q70',
      'QX70',
      'G',
      'QX56',
      'QX4',
      'EX',
      'M',
      'JX',
      'QX50',
      'M35',
      'Q50',
      'QX60',
    ],
  },
  { title: 'Jaguar', models: ['XF', 'XJ', 'X-TYPE', 'S-TYPE'] },
  {
    title: 'Jeep',
    models: ['CHEROKEE', 'LIBERTY', 'COMMANDER', 'GRAND CHEROKEE', 'WRANGLER', 'COMPASS'],
  },
  {
    title: 'Kia',
    models: [
      'CARENS',
      'OPTIMA',
      'SORENTO',
      'QUORIS',
      'CARNIVAL',
      'PICANTO',
      'SOUL',
      'VENGA',
      "CEE'D",
      "PRO CEE'D",
      'SPECTRA',
      'JOICE',
      'CERATO',
      'RIO',
      'SPORTAGE',
      'CLARUS',
      'SEPHIA',
      'MOHAVE',
      'MAGENTIS',
      'SHUMA',
      'OPIRUS',
    ],
  },
  { title: 'Land rover', models: [] },
  {
    title: 'Lexus',
    models: ['ES', 'IS', 'RX', 'GS', 'LS', 'CT', 'GX', 'LX', 'SC'],
  },
  {
    title: 'Mazda',
    models: [
      '323',
      'MAZDA3',
      'MX-5',
      'CX-9',
      '626',
      'MAZDA5',
      'RX-8',
      'TRIBUTE',
      'BT-50',
      'MAZDA6',
      'CX-5',
      'XEDOS 6',
      'MAZDA2',
      'MPV',
      'CX-7',
      'XEDOS 9',
    ],
  },
  {
    title: 'Mercedes',
    models: [
      'A-CLASS',
      'CLS',
      'S-CLASS',
      'GLK-CLASS',
      'B-CLASS',
      'E-CLASS',
      'SL',
      'R-CLASS',
      'C-CLASS',
      'GL-CLASS',
      'SLK',
      'SLS AMG',
      'CLK-CLASS',
      'ML-CLASS',
      'GLA-CLASS',
    ],
  },
  {
    title: 'Mitsubishi',
    models: [
      'CARISMA',
      'GRANDIS',
      'OUTLANDER',
      'SPACE STAR',
      'COLT',
      'L 200',
      'PAJERO',
      'GALANT',
      'LANCER',
      'ASX',
    ],
  },
  {
    title: 'Nissan',
    models: [
      '350 Z',
      'NAVARA',
      'QASHQAI',
      'JUKE',
      'ALMERA',
      'NOTE',
      'TEANA',
      'NP300',
      'MAXIMA',
      'PATHFINDER',
      'TERRANO',
      'MICRA',
      'PATROL',
      'TIIDA',
      'MURANO',
      'PRIMERA',
      'X-TRAIL',
    ],
  },
  {
    title: 'Opel',
    models: [
      'ANTARA',
      'ASTRA',
      'CORSA',
      'TIGRA',
      'INSIGNIA',
      'OMEGA',
      'FRONTERA',
      'ZAFIRA',
      'MOKKA',
      'VECTRA',
      'MERIVA',
      'SPEEDSTER',
      'AGILA',
      'MONTEREY',
    ],
  },
  {
    title: 'Peugeot',
    models: [
      '107',
      '301',
      '207',
      '1007',
      '2008',
      '4008',
      '307',
      '4007',
      '206',
      '408',
      '308',
      '607',
      '208',
      '5008',
      '407',
      '807',
      '3008',
      'RCZ',
      '508',
      'PARTNER',
    ],
  },
  {
    title: 'Renault',
    models: [
      'CLIO',
      'LAGUNA',
      'SCENIC',
      'KOLEOS',
      'ESPACE',
      'LOGAN',
      'SYMBOL',
      'LATITUDE',
      'GRAND',
      'MEGANE',
      'TWINGO',
      'WIND',
      'KANGOO',
      'SANDERO',
      'FLUENCE',
      'DUSTER',
    ],
  },
  {
    title: 'Seat',
    models: ['ALHAMBRA', 'IBIZA', 'ALTEA', 'CORDOBA', 'LEON', 'AROSA', 'EXEO', 'TOLEDO', 'INCA'],
  },
  {
    title: 'Skoda',
    models: ['FABIA', 'RAPID', 'ROOMSTER', 'OCTAVIA', 'SUPERB', 'YETI'],
  },
  {
    title: 'SsangYong',
    models: ['ACTYON', 'RODIUS', 'CHAIRMAN', 'REXTON', 'KORANDO', 'STAVIC', 'MUSSO', 'KYRON'],
  },
  {
    title: 'Subaru',
    models: ['FORESTER', 'LEGACY', 'TRIBECA', 'XV', 'IMPREZA', 'OUTBACK', 'BRZ'],
  },
  {
    title: 'Suzuki',
    models: [
      'GRANDVITARA',
      'SWIFT',
      'KIZASHI',
      'JIMNY',
      'SX4',
      'IGNIS',
      'LIANA',
      'WAGON R+',
      'SPLASH',
    ],
  },
  {
    title: 'Toyota',
    models: [
      'VENZA',
      'COROLLA',
      'LAND CRUISER PRADO',
      'IQ',
      '4RUNNER',
      'GT 86',
      'PREVIA',
      'URBAN CRUISER',
      'AURIS',
      'HIGHLANDER',
      'PRIUS',
      'VERSO',
      'AVENSIS',
      'HILUX',
      'RAV 4',
      'CAMRY',
      'LAND CRUISER',
      'YARIS',
    ],
  },
  {
    title: 'Volkswagen',
    models: [
      'BORA',
      'POLO',
      'TOURAN',
      'UP',
      'GOLF',
      'SCIROCCO',
      'AMAROK',
      'JETTA',
      'SHARAN',
      'PHAETON',
      'PASSAT',
      'TOUAREG',
      'TIGUAN',
    ],
  },
  {
    title: 'Volvo',
    models: [
      'C70',
      'V40',
      'S70',
      'XC60',
      'S40',
      'V70',
      'V50',
      'S60',
      'XC70',
      'C30',
      'S80',
      'XC90',
      'V60',
    ],
  },
  { title: 'ЗАЗ', models: [] },
  { title: 'ТагАЗ', models: [] },
  {
    title: 'Audi',
    models: [
      'A6',
      'A3',
      'TT',
      'Q5',
      'A6/S6',
      'A4',
      'A2',
      'Q7',
      'A8',
      'A5/S5',
      'ALLROAD',
      'A1',
      'A7',
      'Q3',
    ],
  },
  {
    title: 'BMW',
    models: ['5', '3', '7', 'Z4', '1', '4', 'X3', 'X1', '2', '6', 'X5', 'X6'],
  },
  { title: 'Cadillac', models: ['ATS', 'CTS', 'SRX', 'BLS', 'ESCALADE'] },
  {
    title: 'Chevrolet',
    models: [
      'EVANDA',
      'AVEO',
      'LACETTI',
      'TRAILBLAZER',
      'LANOS',
      'CAMARO',
      'MALIBU',
      'CAPTIVA',
      'REZZO',
      'COBALT',
      'SPARK',
      'EPICA',
      'VIVA',
      'CRUZE',
      'TAHOE',
      'ORLANDO',
    ],
  },
  {
    title: 'Citroen',
    models: [
      'BERLINGO',
      'C5',
      'C-CROSSER',
      'DS4',
      'C1',
      'C2',
      'C-ELYSEE',
      'DS5',
      'C3',
      'C6',
      'XSARA',
      'C4',
      'C8',
      'DS3',
    ],
  },
  {
    title: 'Daewoo',
    models: ['GENTRA', 'MATIZ', 'ESPERO', 'WINSTORM', 'LANOS', 'NEXIA', 'LEGANZA'],
  },
  {
    title: 'Fiat',
    models: ['DOBLO', 'ALBEA', 'GRANDE PUNTO', 'BRAVA', 'BARCHETTA'],
  },
  {
    title: 'Ford',
    models: [
      'ESCORT',
      'GALAXY',
      'GRANADA',
      'S-MAX',
      'C-MAX',
      'KA',
      'KUGA',
      'ORION',
      'ECOSPORT',
      'MAVERICK',
      'B-MAX',
      'P 100',
      'FIESTA',
      'MONDEO',
      'EDGE',
      'SCORPIO',
      'FOCUS',
      'RANGER',
      'ESCAPE',
      'SIERRA',
      'FUSION',
      'TOURNEO',
      'GRAND',
      'STREET',
    ],
  },
  { title: 'Ford usa', models: [] },
  {
    title: 'Honda',
    models: [
      'JAZZ',
      'LEGEND',
      'HR-V',
      'RIDGELINE',
      'ACCORD',
      'PILOT',
      'CROSSTOUR',
      'CIVIC',
      'STEPWAGON',
      'ELEMENT',
      'CR-V',
      'STREAM',
      'FR-V',
    ],
  },
  { title: 'Hummer', models: ['HUMMER H2', 'HUMMER H3'] },
  {
    title: 'Hyundai',
    models: [
      'ELANTRA',
      'I30',
      'SONATA',
      'ix35',
      'ACCENT',
      'i30',
      'TUCSON',
      'MATRIX',
      'COUPE',
      'I40',
      'EQUUS',
      'TERRACAN',
      'GENESIS',
      'i40',
      'GETZ',
      'TRAJET',
      'GRANDEUR',
      'SANTA FE',
      'GRAND SANTA FE',
      'VELOSTER',
      'i10',
      'SOLARIS',
      'i20',
      'ix55',
    ],
  },
  {
    title: 'Infiniti',
    models: [
      'FX',
      'M45',
      'Q70',
      'QX70',
      'G',
      'QX56',
      'QX4',
      'EX',
      'M',
      'JX',
      'QX50',
      'M35',
      'Q50',
      'QX60',
    ],
  },
  { title: 'Jaguar', models: ['XF', 'XJ', 'X-TYPE', 'S-TYPE'] },
  {
    title: 'Jeep',
    models: ['CHEROKEE', 'LIBERTY', 'COMMANDER', 'GRAND CHEROKEE', 'WRANGLER', 'COMPASS'],
  },
  {
    title: 'Kia',
    models: [
      'CARENS',
      'OPTIMA',
      'SORENTO',
      'QUORIS',
      'CARNIVAL',
      'PICANTO',
      'SOUL',
      'VENGA',
      "CEE'D",
      "PRO CEE'D",
      'SPECTRA',
      'JOICE',
      'CERATO',
      'RIO',
      'SPORTAGE',
      'CLARUS',
      'SEPHIA',
      'MOHAVE',
      'MAGENTIS',
      'SHUMA',
      'OPIRUS',
    ],
  },
  { title: 'Land rover', models: [] },
  {
    title: 'Lexus',
    models: ['ES', 'IS', 'RX', 'GS', 'LS', 'CT', 'GX', 'LX', 'SC'],
  },
  {
    title: 'Mazda',
    models: [
      '323',
      'MAZDA3',
      'MX-5',
      'CX-9',
      '626',
      'MAZDA5',
      'RX-8',
      'TRIBUTE',
      'BT-50',
      'MAZDA6',
      'CX-5',
      'XEDOS 6',
      'MAZDA2',
      'MPV',
      'CX-7',
      'XEDOS 9',
    ],
  },
  {
    title: 'Mercedes',
    models: [
      'A-CLASS',
      'CLS',
      'S-CLASS',
      'GLK-CLASS',
      'B-CLASS',
      'E-CLASS',
      'SL',
      'R-CLASS',
      'C-CLASS',
      'GL-CLASS',
      'SLK',
      'SLS AMG',
      'CLK-CLASS',
      'ML-CLASS',
      'GLA-CLASS',
    ],
  },
  {
    title: 'Mitsubishi',
    models: [
      'CARISMA',
      'GRANDIS',
      'OUTLANDER',
      'SPACE STAR',
      'COLT',
      'L 200',
      'PAJERO',
      'GALANT',
      'LANCER',
      'ASX',
    ],
  },
  {
    title: 'Nissan',
    models: [
      '350 Z',
      'NAVARA',
      'QASHQAI',
      'JUKE',
      'ALMERA',
      'NOTE',
      'TEANA',
      'NP300',
      'MAXIMA',
      'PATHFINDER',
      'TERRANO',
      'MICRA',
      'PATROL',
      'TIIDA',
      'MURANO',
      'PRIMERA',
      'X-TRAIL',
    ],
  },
  {
    title: 'Opel',
    models: [
      'ANTARA',
      'ASTRA',
      'CORSA',
      'TIGRA',
      'INSIGNIA',
      'OMEGA',
      'FRONTERA',
      'ZAFIRA',
      'MOKKA',
      'VECTRA',
      'MERIVA',
      'SPEEDSTER',
      'AGILA',
      'MONTEREY',
    ],
  },
  {
    title: 'Peugeot',
    models: [
      '107',
      '301',
      '207',
      '1007',
      '2008',
      '4008',
      '307',
      '4007',
      '206',
      '408',
      '308',
      '607',
      '208',
      '5008',
      '407',
      '807',
      '3008',
      'RCZ',
      '508',
      'PARTNER',
    ],
  },
  {
    title: 'Renault',
    models: [
      'CLIO',
      'LAGUNA',
      'SCENIC',
      'KOLEOS',
      'ESPACE',
      'LOGAN',
      'SYMBOL',
      'LATITUDE',
      'GRAND',
      'MEGANE',
      'TWINGO',
      'WIND',
      'KANGOO',
      'SANDERO',
      'FLUENCE',
      'DUSTER',
    ],
  },
  {
    title: 'Seat',
    models: ['ALHAMBRA', 'IBIZA', 'ALTEA', 'CORDOBA', 'LEON', 'AROSA', 'EXEO', 'TOLEDO', 'INCA'],
  },
  {
    title: 'Skoda',
    models: ['FABIA', 'RAPID', 'ROOMSTER', 'OCTAVIA', 'SUPERB', 'YETI'],
  },
  {
    title: 'SsangYong',
    models: ['ACTYON', 'RODIUS', 'CHAIRMAN', 'REXTON', 'KORANDO', 'STAVIC', 'MUSSO', 'KYRON'],
  },
  {
    title: 'Subaru',
    models: ['FORESTER', 'LEGACY', 'TRIBECA', 'XV', 'IMPREZA', 'OUTBACK', 'BRZ'],
  },
  {
    title: 'Suzuki',
    models: [
      'GRANDVITARA',
      'SWIFT',
      'KIZASHI',
      'JIMNY',
      'SX4',
      'IGNIS',
      'LIANA',
      'WAGON R+',
      'SPLASH',
    ],
  },
  {
    title: 'Toyota',
    models: [
      'VENZA',
      'COROLLA',
      'LAND CRUISER PRADO',
      'IQ',
      '4RUNNER',
      'GT 86',
      'PREVIA',
      'URBAN CRUISER',
      'AURIS',
      'HIGHLANDER',
      'PRIUS',
      'VERSO',
      'AVENSIS',
      'HILUX',
      'RAV 4',
      'CAMRY',
      'LAND CRUISER',
      'YARIS',
    ],
  },
  {
    title: 'Volkswagen',
    models: [
      'BORA',
      'POLO',
      'TOURAN',
      'UP',
      'GOLF',
      'SCIROCCO',
      'AMAROK',
      'JETTA',
      'SHARAN',
      'PHAETON',
      'PASSAT',
      'TOUAREG',
      'TIGUAN',
    ],
  },
  {
    title: 'Volvo',
    models: [
      'C70',
      'V40',
      'S70',
      'XC60',
      'S40',
      'V70',
      'V50',
      'S60',
      'XC70',
      'C30',
      'S80',
      'XC90',
      'V60',
    ],
  },
  { title: 'ЗАЗ', models: [] },
  { title: 'ТагАЗ', models: [] },
]





